# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: dzdd
email: donghui_ncepu@126.com
description: > # this means to ignore newlines until "baseurl:"
  路漫漫其修远兮，吾将上下而求索。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://DNT1024.github.io" # the base hostname & protocol for your site
github_username:  DNT1024

destination: _deploy

# Build settings
markdown: kramdown

panginate: 5
paginate_path: "page:num"

